# <span style='color:black'> <center>Trabajando datos con Numpy</center> </span>
## 1. Numpy Arrays
<p><img src="https://www.ucatalunya.edu.co/img/blog/herramientas-de-analisis-de-datos.jpg" width="850"</p>

# La librería de Numpy

Numpy es una de las librería más utilizadas dentro de python, utilizada para cálculo numérico y análisis de datos. Una de sus características principales es el poder manejar un gran volumen de datos.
- Herramientas lectura y escritura de datos matriciales.
- Funciones matemáticas que realizan operaciones sobre la data dentro de un arreglo sin nececidad de utilizar iteradores.
- Capacidades para trabajar temas de álgebra lineal y generación de números aleatorios.

## Objetos multidimensionales de Numpy

Los **arrays** son objetos caracterísitcos de **Numpy**, los cuales son una manera rápida y flexible de contener grandes cantidades de datos dentro de Python. Los **arrays** permiten realizar operaciones matemáticas por bloque usando una sintaxis simliar a como se realizan operaciones entre escalares.

Para crear un arreglo n-dimensional, necesitamos importar la librería **Numpy** y utilizar la función *array*.

In [1]:
#importar la libreria numpy

import numpy as np

#crear un array dentro de una variable

datos = np.array([[1,10,3], [1,10,4], [1,2,5]])


#observamos el array
print('En forma de arreglo:\n',datos)

En forma de arreglo:
 [[ 1 10  3]
 [ 1 10  4]
 [ 1  2  5]]


Otra forma de definir un array es a partir de una o varias listas.

In [2]:
#Crear un array unidimensional a partir de una lista

mi_lista = [1,2,3,4,5]

mi_arreglo = np.array(mi_lista)

print('En forma de Lista: \n',mi_lista)

print('En forma de arreglo:\n',mi_arreglo)

En forma de Lista: 
 [1, 2, 3, 4, 5]
En forma de arreglo:
 [1 2 3 4 5]


In [3]:
#Crear un array bidimensional a partir de varias listas
mi_lista = [[1,2,3,4,5], [6,7,8,9,10], [1,2,3,4,5]]
print('En forma de Lista: \n',mi_lista)

mi_arreglo = np.array(mi_lista)
print('En forma de arreglo:\n',mi_arreglo)

En forma de Lista: 
 [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5]]
En forma de arreglo:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


### Propiedades de los arrays

Podemos conocer ciertas propiedades de los numpy arrays.
- **shape:** devuelve la forma de un array (el número de elementos en cada dimensión).
- **ndim:** devuelve el número de dimensiones que tiene un array.
- **size:**  devuelve el conteo de elemento dentro de un array.
- **dtype:** devuelve el tipo de dato contenido dentro del array.

In [5]:
#Forma de un numpy array

print('shape:', mi_arreglo.shape)

#Dimensión de un numpy array

print('Numero de dimensiones del arreglo: ', mi_arreglo.ndim)

#Tamaño de un numpy array

print('El size o numero total de elementos en el arreglo es: ',mi_arreglo.size)

#Tipo de dato dentro de un numpy array

print('El typo de datos en el arreglo es:', mi_arreglo.dtype)


shape: (3, 5)
Numero de dimensiones del arreglo:  2
El size o numero total de elementos en el arreglo es:  15
El typo de datos en el arreglo es: int32


El tipo de dato dentro puede definirse a la hora de construir el array.

In [7]:
mi_arreglo2 = np.array(mi_lista, dtype=np.int16)

print('El tipo de datos en el arreglo es:', mi_arreglo2.dtype)


El tipo de datos en el arreglo es: int16


Es posible creas numpy arrays vacios o llenos de 0 para crear un objeto que será editado posteriormente.

In [8]:
#numpy arrays que contiene 0 en todas las entradas

arreglo_cero = np.zeros((3,6), dtype=np.float16)
print(arreglo_cero)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
#numpy arrays que contiene 1 en todas las entradas

arreglo_unos = np.ones((4,3), dtype=np.int16)
arreglo_unos

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [11]:
#numpy arrays vacio

arreglo_vacio = np.empty((4,2))
print('arreglo_vacio:\n', arreglo_vacio)


arreglo_vacio2 = np.array([])
print('arreglo_vacio2:\n', arreglo_vacio2)



arreglo_vacio:
 [[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 7.56595054e-307]
 [7.56596412e-307 1.42419938e-306]
 [7.56603881e-307 8.34402697e-309]]
arreglo_vacio2:
 []


### Arrays que contienen secuencias de números

Los métodos **arange** y **linspace** se pueden utilizar para crear arreglos a partir de secuencias de valores.

- **arange**: genera un conjunto de números entre un valor de inicio y uno final, pudiendo especificar un incremento entre los valores.
- **linspace**: genera un array NumPy formado por n números equiespaciados entre dos dados

In [12]:
# array de una secuencia de 20 números con forma 4x5

print(np.arange(20))
print('\n')

# reshape
print(np.arange(20).reshape(4,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [13]:
# array de 50 números entre 10 y 20
print(np.linspace(10, 20))

print(np.linspace(10, 20).size)


# array de 20 números entre 0 y 10

print(np.linspace(0, 20, 20))

print(np.linspace(0, 20, 20).size)


# array de 100 números entre 0 y 100

print(np.linspace(0, 100, 10))

print(np.linspace(0, 20, 20).size)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]
50
[ 0.          1.05263158  2.10526316  3.15789474  4.21052632  5.26315789
  6.31578947  7.36842105  8.42105263  9.47368421 10.52631579 11.57894737
 12.63157895 13.68421053 14.73684211 15.78947368 16.84210526 17.89473684
 18.94736842 20.        ]
20
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
20


## Operando arrays

Podemos utilizar los operadores aritméticos para realizar operaciones sobre los numpy arrays.

In [14]:
# sumando y multiplicando un escalar a un array

datos1 = np.linspace(15,25,11)
print(datos1)

print(datos1 + 10)

print(datos1 * 3)

[15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25.]
[25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.]
[45. 48. 51. 54. 57. 60. 63. 66. 69. 72. 75.]


In [15]:
# sumando 2 arrays (la suma se hará entrada a entrada)

datos1 = np.arange(10,30,2)
datos2 = np.arange(30,40,1)

print(datos1)
print(datos2)

print(datos1 + datos2)


[10 12 14 16 18 20 22 24 26 28]
[30 31 32 33 34 35 36 37 38 39]
[40 43 46 49 52 55 58 61 64 67]


In [16]:
# multiplicando 2 arrays (la multiplicación se hará entrada a entrada)

print(datos1 * datos2)


[ 300  372  448  528  612  700  792  888  988 1092]


In [17]:
# producto punto 2 arrays 

print(np.dot(datos1, datos2))

6720


In [18]:
# producto cruz 2 arrays (Determinantes de Matrices)

#(a1, a2, a3) X (b1, b2, b3) = (a2*b3 - a3*b2, a3*b1 - a1*b3, a1*b2 - a2*b1)

datos1 = np.array([2,6,9])
datos2 = np.arange(4,7,1)

print(datos1)
print(datos2)

print(np.cross(datos1, datos2))

[2 6 9]
[4 5 6]
[ -9  24 -14]
